module CatalogSyncTest exposing (..)

import JsonRender.CatalogSync as CatalogSync
import Review.Test
import Test exposing (..)


sampleSchemaJson : String
sampleSchemaJson =
    """{"components":{"Card":{"props":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]},"description":"A card","slots":["default"]}},"actions":{"press":{"params":{"type":"object","properties":{},"required":[]},"description":"Generic button press"}}}"""


baseConfig : CatalogSync.Config
baseConfig =
    { schemaJson = sampleSchemaJson
    , catalogNamespace = "Catalog"
    }


{-| A Card component module whose scaffold matches what ElmCodeGen generates
for the sampleSchemaJson Card schema. The view function is user-owned.
-}
validCardSource : String
validCardSource =
    """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "card"
"""


validButtonSource : String
validButtonSource =
    """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias ButtonProps
   - type alias ButtonBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Button exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias ButtonProps =
    { label : String }


type alias ButtonBindings msg =
    { label : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String ButtonProps
propsDecoder =
    ResolvedValue.succeed ButtonProps |> ResolvedValue.required "label" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> ButtonBindings msg
bindingsDecoder =
    Bind.succeed ButtonBindings |> Bind.bindableTyped "label" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext ButtonProps (ButtonBindings msg) msg -> Html msg
view ctx =
    Html.text "button"
"""


suite : Test
suite =
    describe "CatalogSync rule"
        [ test "reports all missing modules in a single error" <|
            \_ ->
                """module Main exposing (..)
import Html
main = Html.text "hello"
"""
                    |> Review.Test.run (CatalogSync.rule baseConfig)
                    |> Review.Test.expectGlobalErrors
                        [ { message = "Missing modules: Card, Registry, Actions"
                          , details =
                                [ "Create these files: src/Catalog/Components/Card.elm, src/Catalog/Registry.elm, src/Catalog/Actions.elm"
                                , "Quick stub command:\n\nmkdir -p src/Catalog src/Catalog/Components && \\\n  echo 'module Catalog.Components.Card exposing (..)' > src/Catalog/Components/Card.elm && \\\n  echo 'module Catalog.Registry exposing (..)' > src/Catalog/Registry.elm && \\\n  echo 'module Catalog.Actions exposing (..)' > src/Catalog/Actions.elm"
                                , "Then run elm-review --fix to fill them in."
                                ]
                          }
                        ]
        , test "reports missing registry and actions in a single error" <|
            \_ ->
                [ validCardSource ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectGlobalErrors
                        [ { message = "Missing modules: Registry, Actions"
                          , details =
                                [ "Create these files: src/Catalog/Registry.elm, src/Catalog/Actions.elm"
                                , "Quick stub command:\n\nmkdir -p src/Catalog && \\\n  echo 'module Catalog.Registry exposing (..)' > src/Catalog/Registry.elm && \\\n  echo 'module Catalog.Actions exposing (..)' > src/Catalog/Actions.elm"
                                , "Then run elm-review --fix to fill them in."
                                ]
                          }
                        ]
        , test "no errors when component and registry exist" <|
            \_ ->
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectNoErrors
        , test "reports incomplete registry" <|
            \_ ->
                let
                    twoComponentSchema =
                        """{"components":{"Card":{"props":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]},"description":"A card","slots":["default"]},"Button":{"props":{"type":"object","properties":{"label":{"type":"string"}},"required":["label"]},"description":"A button","slots":[]}}}"""

                    twoConfig =
                        { schemaJson = twoComponentSchema
                        , catalogNamespace = "Catalog"
                        }
                in
                [ validCardSource
                , validButtonSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule twoConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Registry"
                          , [ Review.Test.error
                                { message = "Registry is missing components: Button"
                                , details =
                                    [ "The registry module does not include all catalog components."
                                    , "Accept the fix to regenerate it."
                                    ]
                                , under = "module Catalog.Registry exposing (registry)"
                                }
                                |> Review.Test.whenFixed """module Catalog.Registry exposing (registry)

import Dict
import JsonRender.Render exposing (Registry)
import Catalog.Components.Button
import Catalog.Components.Card


registry : Registry msg
registry =
    { components =
        Dict.fromList
            [ ( "Button", Catalog.Components.Button.component ), ( "Card", Catalog.Components.Card.component ) ]
    , functions = Dict.empty
    }
"""
                            ]
                          )
                        ]
        , test "reports missing actions module" <|
            \_ ->
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectGlobalErrors
                        [ { message = "Missing modules: Actions"
                          , details =
                                [ "Create these files: src/Catalog/Actions.elm"
                                , "Quick stub command:\n\nmkdir -p src/Catalog && \\\n  echo 'module Catalog.Actions exposing (..)' > src/Catalog/Actions.elm"
                                , "Then run elm-review --fix to fill them in."
                                ]
                          }
                        ]
        , test "no errors when component, registry, and actions modules exist with correct type" <|
            \_ ->
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectNoErrors
        , test "reports outdated actions module when variants are wrong" <|
            \_ ->
                let
                    schemaWithTwoActions =
                        """{"components":{"Card":{"props":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]},"description":"A card","slots":["default"]}},"actions":{"press":{"params":{"type":"object","properties":{},"required":[]},"description":"Generic button press"},"export":{"params":{"type":"object","properties":{"format":{"type":"string"}},"required":["format"]},"description":"Export data"}}}"""

                    twoActionsConfig =
                        { schemaJson = schemaWithTwoActions
                        , catalogNamespace = "Catalog"
                        }
                in
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..))
type Action = Press
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule twoActionsConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Actions"
                          , [ Review.Test.error
                                { message = "Actions module is missing variants: Export, actionConfig, handleAction"
                                , details =
                                    [ "The Actions module does not match the catalog actions."
                                    , "Accept the fix to regenerate it."
                                    ]
                                , under = "module Catalog.Actions exposing (Action(..))"
                                }
                                |> Review.Test.whenFixed ("module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)\n\nimport Dict exposing (Dict)\nimport Json.Decode as Decode\nimport Json.Encode exposing (Value)\nimport JsonRender.Actions as Actions\n\n\ntype alias ExportParams =\n    { format : String }\n\n\ntype Action\n    = Export ExportParams\n    | Press\n\ndecodeAction : String -> Dict String Value -> Result String Action\ndecodeAction name params =\n    case name of\n        \"export\" ->\n            case Dict.get \"format\" params of\n                Just format_raw ->\n                    case Decode.decodeValue Decode.string format_raw of\n                        Ok format ->\n                            Ok (Export { format = format })\n\n                        Err _ ->\n                            Err \"format must be a String\"\n\n                Nothing ->\n                    Err \"missing required param format\"\n\n        \"press\" ->\n            Ok Press\n\n        _ ->\n            Err (\"Unknown action: \" ++ name)\n\n\nhandleAction : Action -> Actions.Model -> ( Actions.Model, Cmd (Actions.Msg Action) )\nhandleAction action model =\n    ()\n\nactionConfig : Actions.ActionConfig Action\nactionConfig =\n    { handleAction = handleAction, decodeAction = decodeAction }")
                            ]
                          )
                        ]
        , test "no errors when actions module has all variants including decodeAction" <|
            \_ ->
                let
                    schemaWithTwoActions =
                        """{"components":{"Card":{"props":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]},"description":"A card","slots":["default"]}},"actions":{"press":{"params":{"type":"object","properties":{},"required":[]},"description":"Generic button press"},"export":{"params":{"type":"object","properties":{"format":{"type":"string"}},"required":["format"]},"description":"Export data"}}}"""

                    twoActionsConfig =
                        { schemaJson = schemaWithTwoActions
                        , catalogNamespace = "Catalog"
                        }
                in
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Export ExportParams | Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule twoActionsConfig)
                    |> Review.Test.expectNoErrors
        , test "reports missing actionConfig and handleAction when variants are correct" <|
            \_ ->
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), decodeAction)
type Action = Press
decodeAction name params = Ok Press
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Actions"
                          , [ Review.Test.error
                                { message = "Actions module is missing actionConfig, handleAction"
                                , details =
                                    [ "The Actions module does not match the catalog actions."
                                    , "Accept the fix to regenerate it."
                                    ]
                                , under = "module Catalog.Actions exposing (Action(..), decodeAction)"
                                }
                                |> Review.Test.whenFixed ("module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)\n\nimport Dict exposing (Dict)\nimport Json.Decode as Decode\nimport Json.Encode exposing (Value)\nimport JsonRender.Actions as Actions\n\n\ntype Action\n    = Press\n\ndecodeAction : String -> Dict String Value -> Result String Action\ndecodeAction name params =\n    case name of\n        \"press\" ->\n            Ok Press\n\n        _ ->\n            Err (\"Unknown action: \" ++ name)\n\n\nhandleAction : Action -> Actions.Model -> ( Actions.Model, Cmd (Actions.Msg Action) )\nhandleAction action model =\n    ()\n\nactionConfig : Actions.ActionConfig Action\nactionConfig =\n    { handleAction = handleAction, decodeAction = decodeAction }")
                            ]
                          )
                        ]
        , test "no actions in catalog means no actions module needed" <|
            \_ ->
                let
                    noActionsSchema =
                        """{"components":{"Card":{"props":{"type":"object","properties":{"title":{"type":"string"}},"required":["title"]},"description":"A card","slots":["default"]}}}"""

                    noActionsConfig =
                        { schemaJson = noActionsSchema
                        , catalogNamespace = "Catalog"
                        }
                in
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule noActionsConfig)
                    |> Review.Test.expectNoErrors
        , test "fixes stub actions module" <|
            \_ ->
                [ validCardSource
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (..)
placeholder = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Actions"
                          , [ Review.Test.error
                                { message = "Actions module is missing variants: Press, actionConfig, handleAction"
                                , details =
                                    [ "The Actions module does not match the catalog actions."
                                    , "Accept the fix to regenerate it."
                                    ]
                                , under = "module Catalog.Actions exposing (..)"
                                }
                                |> Review.Test.whenFixed ("module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)\n\nimport Dict exposing (Dict)\nimport Json.Decode as Decode\nimport Json.Encode exposing (Value)\nimport JsonRender.Actions as Actions\n\n\ntype Action\n    = Press\n\ndecodeAction : String -> Dict String Value -> Result String Action\ndecodeAction name params =\n    case name of\n        \"press\" ->\n            Ok Press\n\n        _ ->\n            Err (\"Unknown action: \" ++ name)\n\n\nhandleAction : Action -> Actions.Model -> ( Actions.Model, Cmd (Actions.Msg Action) )\nhandleAction action model =\n    ()\n\nactionConfig : Actions.ActionConfig Action\nactionConfig =\n    { handleAction = handleAction, decodeAction = decodeAction }")
                            ]
                          )
                        ]
        , test "reports outdated component when scaffold differs" <|
            \_ ->
                [ """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)
type alias CardProps = { title : Int }
propsDecoder = identity
component = ()
view ctx = Html.text "my card"
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Components.Card"
                          , [ Review.Test.error
                                { message = "Card component types are out of sync with the catalog"
                                , details =
                                    [ "The generated types and decoders in this module don't match the catalog schema."
                                    , "Accept the fix to regenerate them. Your view function will be preserved."
                                    ]
                                , under = "module Catalog.Components.Card exposing (component)"
                                }
                                |> Review.Test.whenFixed """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)
type alias CardProps =
    { title : String }

propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string

component : Component msg
component =
    register propsDecoder bindingsDecoder view

bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


view ctx = Html.text "my card"
"""
                            ]
                          )
                        ]
        , test "fixes stub component module" <|
            \_ ->
                [ """module Catalog.Components.Card exposing (..)
placeholder = ()
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Components.Card"
                          , [ Review.Test.error
                                { message = "Card component is missing view function"
                                , details =
                                    [ "This module should contain types, decoders, and a view function matching the catalog."
                                    , "Accept the fix to generate the correct code with a view placeholder."
                                    ]
                                , under = "module Catalog.Components.Card exposing (..)"
                                }
                                |> Review.Test.whenFixed
                                    ("""{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    ()
""")
                            ]
                          )
                        ]
        , test "no error when declarations are present but reordered" <|
            \_ ->
                [ """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


component : Component msg
component =
    register propsDecoder bindingsDecoder view


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


type alias CardProps =
    { title : String }


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "card"
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectNoErrors
        , test "fixes only the outdated declaration, preserves others" <|
            \_ ->
                [ """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : Int }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "my card"
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Components.Card"
                          , [ Review.Test.error
                                { message = "Card component types are out of sync with the catalog"
                                , details =
                                    [ "The generated types and decoders in this module don't match the catalog schema."
                                    , "Accept the fix to regenerate them. Your view function will be preserved."
                                    ]
                                , under = "module Catalog.Components.Card exposing (component)"
                                }
                                |> Review.Test.whenFixed """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "my card"
"""
                            ]
                          )
                        ]
        , test "inserts missing declaration before view" <|
            \_ ->
                [ """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "my card"
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectErrorsForModules
                        [ ( "Catalog.Components.Card"
                          , [ Review.Test.error
                                { message = "Card component types are out of sync with the catalog"
                                , details =
                                    [ "The generated types and decoders in this module don't match the catalog schema."
                                    , "Accept the fix to regenerate them. Your view function will be preserved."
                                    ]
                                , under = "module Catalog.Components.Card exposing (component)"
                                }
                                |> Review.Test.whenFixed """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    Html.text "my card"
"""
                            ]
                          )
                        ]
        , test "no error when user adds helper functions between declarations" <|
            \_ ->
                [ """{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias CardProps
   - type alias CardBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}
module Catalog.Components.Card exposing (component)

import Dict exposing (Dict)
import Html exposing (Html, div, h3, text)
import Html.Attributes exposing (class)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias CardProps =
    { title : String }


type alias CardBindings msg =
    { title : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String CardProps
propsDecoder =
    ResolvedValue.succeed CardProps |> ResolvedValue.required "title" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> CardBindings msg
bindingsDecoder =
    Bind.succeed CardBindings |> Bind.bindableTyped "title" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder view


myHelper : String -> String
myHelper s =
    String.toUpper s


view : ComponentContext CardProps (CardBindings msg) msg -> Html msg
view ctx =
    div [ class "jr-card" ] [ h3 [] [ text (myHelper ctx.props.title) ] ]
"""
                , """module Catalog.Registry exposing (registry)
import Dict
import Catalog.Components.Card
registry = Dict.fromList [ ( "Card", Catalog.Components.Card.component ) ]
"""
                , """module Catalog.Actions exposing (Action(..), actionConfig, decodeAction, handleAction)
type Action = Press
actionConfig = ()
decodeAction name params = Ok Press
handleAction action model = ()
"""
                ]
                    |> Review.Test.runOnModules (CatalogSync.rule baseConfig)
                    |> Review.Test.expectNoErrors
        ]
