{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type GreenOrRedOrYellowOrBlueOrGray
   - greenOrRedOrYellowOrBlueOrGrayFromString
   - type alias BadgeProps
   - propsDecoder
   - component
-}


module Catalog.Components.Badge exposing (BadgeProps, component, propsDecoder)

import Dict exposing (Dict)
import Html exposing (Html, span, text)
import Html.Attributes exposing (class)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type GreenOrRedOrYellowOrBlueOrGray
    = Green
    | Red
    | Yellow
    | Blue
    | Gray


greenOrRedOrYellowOrBlueOrGrayFromString : String -> Result String GreenOrRedOrYellowOrBlueOrGray
greenOrRedOrYellowOrBlueOrGrayFromString str =
    case str of
        "green" ->
            Ok Green

        "red" ->
            Ok Red

        "yellow" ->
            Ok Yellow

        "blue" ->
            Ok Blue

        "gray" ->
            Ok Gray

        _ ->
            Err ("Unknown value: " ++ str ++ ". Expected one of: green, red, yellow, blue, gray")


greenOrRedOrYellowOrBlueOrGrayToString : GreenOrRedOrYellowOrBlueOrGray -> String
greenOrRedOrYellowOrBlueOrGrayToString value =
    case value of
        Green ->
            "green"

        Red ->
            "red"

        Yellow ->
            "yellow"

        Blue ->
            "blue"

        Gray ->
            "gray"


type alias BadgeProps =
    { color : Maybe GreenOrRedOrYellowOrBlueOrGray, label : String }


propsDecoder : Dict String ResolvedValue -> Result String BadgeProps
propsDecoder =
    ResolvedValue.succeed BadgeProps
        |> ResolvedValue.optional
            "color"
            (\rv -> ResolvedValue.string rv |> Result.andThen greenOrRedOrYellowOrBlueOrGrayFromString)
            Nothing
        |> ResolvedValue.required "label" ResolvedValue.string


component : Component msg
component =
    register propsDecoder (\_ -> ()) (\_ -> ()) view


view : ComponentContext BadgeProps () () msg -> Html msg
view ctx =
    let
        colorClass =
            case ctx.props.color of
                Just c ->
                    "jr-badge-" ++ greenOrRedOrYellowOrBlueOrGrayToString c

                Nothing ->
                    "jr-badge-gray"
    in
    span [ class ("jr-badge " ++ colorClass) ] [ text ctx.props.label ]
