{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type PrimaryOrSecondaryOrDanger
   - primaryOrSecondaryOrDangerFromString
   - type alias ButtonProps
   - propsDecoder
   - component
-}


module Catalog.Components.Button exposing (ButtonProps, component, propsDecoder, viewStateless)

import Dict exposing (Dict)
import Html exposing (Html, button, text)
import Html.Attributes exposing (class)
import Html.Events
import JsonRender.Events as Events
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type PrimaryOrSecondaryOrDanger
    = Primary
    | Secondary
    | Danger


primaryOrSecondaryOrDangerFromString : String -> Result String PrimaryOrSecondaryOrDanger
primaryOrSecondaryOrDangerFromString str =
    case str of
        "primary" ->
            Ok Primary

        "secondary" ->
            Ok Secondary

        "danger" ->
            Ok Danger

        _ ->
            Err ("Unknown value: " ++ str ++ ". Expected one of: primary, secondary, danger")


type alias ButtonProps =
    { label : String, variant : Maybe PrimaryOrSecondaryOrDanger }


propsDecoder : Dict String ResolvedValue -> Result String ButtonProps
propsDecoder =
    ResolvedValue.succeed ButtonProps
        |> ResolvedValue.required "label" ResolvedValue.string
        |> ResolvedValue.optional
            "variant"
            (\rv -> ResolvedValue.string rv |> Result.andThen primaryOrSecondaryOrDangerFromString)
            Nothing


variantToClass : Maybe PrimaryOrSecondaryOrDanger -> String
variantToClass variant =
    case variant of
        Just Secondary ->
            "jr-button-secondary"

        Just Danger ->
            "jr-button-danger"

        _ ->
            "jr-button-primary"


component : Component msg
component =
    register propsDecoder (\_ -> ()) (\_ -> ()) view


viewStateless : ButtonProps -> (String -> msg) -> Html msg
viewStateless props emit =
    button
        [ class ("jr-button " ++ variantToClass props.variant)
        , Html.Events.onClick (emit "press")
        ]
        [ text props.label ]


view : ComponentContext ButtonProps () () msg -> Html msg
view ctx =
    button
        [ class ("jr-button " ++ variantToClass ctx.props.variant)
        , Events.onClick (ctx.emit "press")
        ]
        [ text ctx.props.label ]
