{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias ImageProps
   - type alias ImageBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}


module Catalog.Components.Image exposing (ImageProps, component, propsDecoder)

import Dict exposing (Dict)
import Html exposing (Html, img)
import Html.Attributes exposing (alt, class, src)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias ImageProps =
    { alt : String, src : String }


type alias ImageBindings msg =
    { alt : Maybe (String -> EventHandle msg), src : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String ImageProps
propsDecoder =
    ResolvedValue.succeed ImageProps
        |> ResolvedValue.required "alt" ResolvedValue.string
        |> ResolvedValue.required "src" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> ImageBindings msg
bindingsDecoder =
    Bind.succeed ImageBindings
        |> Bind.bindableTyped "alt" Json.Encode.string
        |> Bind.bindableTyped "src" Json.Encode.string


component : Component msg
component =
    register propsDecoder bindingsDecoder (\_ -> ()) view


view : ComponentContext ImageProps (ImageBindings msg) () msg -> Html msg
view ctx =
    img
        [ src ctx.props.src
        , alt ctx.props.alt
        , class "jr-image"
        ]
        []
