{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias InputProps
   - type alias InputBindings
   - type alias InputValidation
   - propsDecoder
   - bindingsDecoder
   - validationDecoder
   - component
-}


module Catalog.Components.Input exposing (InputBindings, InputProps, InputValidation, bindingsDecoder, component, propsDecoder, validationDecoder)

import Dict exposing (Dict)
import Html exposing (Html, div, input, label, p, text)
import Html.Attributes exposing (class, placeholder, type_)
import Json.Encode exposing (Value)
import JsonRender.Bind as Bind
import JsonRender.Events as Events exposing (EventHandle)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)
import JsonRender.Validation as Validation exposing (FieldValidation, ValidateOn(..))


type alias InputProps =
    { label : Maybe String, placeholder : Maybe String, value : Maybe String }


type alias InputBindings msg =
    { value : Maybe (String -> EventHandle msg) }


type alias InputValidation =
    { value : Maybe FieldValidation }


propsDecoder : Dict String ResolvedValue -> Result String InputProps
propsDecoder =
    ResolvedValue.succeed InputProps
        |> ResolvedValue.optional "label" ResolvedValue.string Nothing
        |> ResolvedValue.optional "placeholder" ResolvedValue.string Nothing
        |> ResolvedValue.optional "value" ResolvedValue.string Nothing


bindingsDecoder : Dict String (Value -> EventHandle msg) -> InputBindings msg
bindingsDecoder =
    Bind.succeed InputBindings |> Bind.bindableTyped "value" Json.Encode.string


validationDecoder : Dict String FieldValidation -> InputValidation
validationDecoder =
    Validation.succeed InputValidation |> Validation.field "value"


component : Component msg
component =
    register propsDecoder bindingsDecoder validationDecoder view


view : ComponentContext InputProps (InputBindings msg) InputValidation msg -> Html msg
view ctx =
    div [ class "jr-input-wrapper" ]
        ((case ctx.props.label of
            Just lbl ->
                [ label [ class "jr-input-label" ] [ text lbl ] ]

            Nothing ->
                []
         )
            ++ [ input
                    [ type_ "text"
                    , class "jr-input"
                    , placeholder (Maybe.withDefault "" ctx.props.placeholder)
                    , Html.Attributes.value (Maybe.withDefault "" ctx.props.value)
                    , case ctx.bindings.value of
                        Just setValue ->
                            Events.onInput (\s -> setValue s)

                        Nothing ->
                            class ""
                    , Events.onBlur
                        (if ctx.validateOn == OnBlur then
                            ctx.validateAndEmit "blur"

                         else
                            ctx.emit "blur"
                        )
                    ]
                    []
               , case ctx.validation.value of
                    Just fv ->
                        if not (List.isEmpty fv.errors) && fv.touched then
                            p [ class "jr-input-error" ]
                                [ text (List.head fv.errors |> Maybe.withDefault "") ]

                        else
                            text ""

                    Nothing ->
                        text ""
               ]
        )
