{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias SelectProps
   - type alias SelectBindings
   - propsDecoder
   - bindingsDecoder
   - component
-}


module Catalog.Components.Select exposing (component, view)

import Dict exposing (Dict)
import Html exposing (Html, button, div, input, li, text, ul)
import Html.Attributes exposing (class, placeholder, type_, value)
import Html.Events
import Json.Encode exposing (Value)
import JsonRender.Actions as Actions
import JsonRender.Bind as Bind
import JsonRender.Events exposing (EventHandle)
import JsonRender.Internal.Effect exposing (Effect(..))
import JsonRender.Render exposing (Component, ComponentContext, registerStateful)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias SelectProps =
    { label : Maybe String, options : List String, placeholder : Maybe String, value : String }


type alias SelectBindings msg =
    { value : Maybe (String -> EventHandle msg) }


propsDecoder : Dict String ResolvedValue -> Result String SelectProps
propsDecoder =
    ResolvedValue.succeed SelectProps
        |> ResolvedValue.optional "label" ResolvedValue.string Nothing
        |> ResolvedValue.required "options" (ResolvedValue.list ResolvedValue.string)
        |> ResolvedValue.optional "placeholder" ResolvedValue.string Nothing
        |> ResolvedValue.required "value" ResolvedValue.string


bindingsDecoder : Dict String (Value -> EventHandle msg) -> SelectBindings msg
bindingsDecoder =
    Bind.succeed SelectBindings |> Bind.bindableTyped "value" Json.Encode.string


type alias State =
    { open : Bool
    , query : String
    , focusedIndex : Int
    }


type LocalMsg
    = ToggleOpen
    | Close
    | SetQuery String
    | FocusItem Int
    | SelectOption String


component : Component (Actions.Msg action)
component =
    registerStateful propsDecoder
        bindingsDecoder
        (\_ -> ())
        { init = \_ -> { open = False, query = "", focusedIndex = 0 }
        , update = update
        , view = selectView
        , onPropsChange = Just onPropsChange
        , portSubscriptions =
            [ ( "clickOutside", \_ -> Close ) ]
        }


onPropsChange : SelectProps -> State -> ( State, List (Effect (Actions.Msg action) LocalMsg) )
onPropsChange _ state =
    ( { state | open = False, query = "" }, [] )


update : LocalMsg -> State -> ComponentContext SelectProps (SelectBindings (Actions.Msg action)) () (Actions.Msg action) -> ( State, List (Effect (Actions.Msg action) LocalMsg) )
update msg state ctx =
    case msg of
        ToggleOpen ->
            ( { state | open = not state.open, query = "", focusedIndex = 0 }, [] )

        Close ->
            ( { state | open = False, query = "" }, [] )

        SetQuery q ->
            ( { state | query = q, focusedIndex = 0 }, [] )

        FocusItem i ->
            ( { state | focusedIndex = i }, [] )

        SelectOption opt ->
            ( { state | open = False, query = "" }
            , case ctx.bindings.value of
                Just setValue ->
                    [ Emit (setValue opt), Emit (ctx.emit "change") ]

                Nothing ->
                    [ Emit (ctx.emit "change") ]
            )


filteredOptions : String -> List String -> List String
filteredOptions query options =
    if String.isEmpty query then
        options

    else
        List.filter
            (\opt -> String.contains (String.toLower query) (String.toLower opt))
            options


selectView : State -> SelectProps -> (LocalMsg -> Actions.Msg action) -> List (Html (Actions.Msg action)) -> Html (Actions.Msg action)
selectView state props toMsg _ =
    div [ class "jr-select" ]
        ([ case props.label of
            Just lbl ->
                Html.label [ class "jr-select-label" ] [ text lbl ]

            Nothing ->
                text ""
         , Html.map toMsg
            (button
                [ class "jr-select-trigger"
                , Html.Events.onClick ToggleOpen
                ]
                [ text
                    (if String.isEmpty props.value then
                        Maybe.withDefault "Select..." props.placeholder

                     else
                        props.value
                    )
                ]
            )
         ]
            ++ (if state.open then
                    [ Html.map toMsg (dropdownView state props) ]

                else
                    []
               )
        )


dropdownView : State -> SelectProps -> Html LocalMsg
dropdownView state props =
    let
        visible =
            filteredOptions state.query props.options
    in
    div [ class "jr-select-dropdown" ]
        [ input
            [ type_ "text"
            , class "jr-select-search"
            , placeholder "Search..."
            , value state.query
            , Html.Events.onInput SetQuery
            ]
            []
        , ul [ class "jr-select-options" ]
            (List.indexedMap
                (\i opt ->
                    li
                        [ class
                            ("jr-select-option"
                                ++ (if i == state.focusedIndex then
                                        " jr-select-option-focused"

                                    else
                                        ""
                                   )
                            )
                        , Html.Events.onClick (SelectOption opt)
                        , Html.Events.onMouseEnter (FocusItem i)
                        ]
                        [ text opt ]
                )
                visible
            )
        , if List.isEmpty visible then
            div [ class "jr-select-empty" ] [ text "No matches" ]

          else
            text ""
        ]


view : ComponentContext SelectProps (SelectBindings (Actions.Msg action)) () (Actions.Msg action) -> Html (Actions.Msg action)
view _ =
    text ""
