{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type VerticalOrHorizontal
   - verticalOrHorizontalFromString
   - type alias StackProps
   - propsDecoder
   - component
-}


module Catalog.Components.Stack exposing (StackProps, component, propsDecoder)

import Dict exposing (Dict)
import Html exposing (Html, div)
import Html.Attributes exposing (class, style)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type VerticalOrHorizontal
    = Vertical
    | Horizontal


verticalOrHorizontalFromString : String -> Result String VerticalOrHorizontal
verticalOrHorizontalFromString str =
    case str of
        "vertical" ->
            Ok Vertical

        "horizontal" ->
            Ok Horizontal

        _ ->
            Err ("Unknown value: " ++ str ++ ". Expected one of: vertical, horizontal")


type alias StackProps =
    { direction : Maybe VerticalOrHorizontal, gap : Maybe Int }


propsDecoder : Dict String ResolvedValue -> Result String StackProps
propsDecoder =
    ResolvedValue.succeed StackProps
        |> ResolvedValue.optional
            "direction"
            (\rv -> ResolvedValue.string rv |> Result.andThen verticalOrHorizontalFromString)
            Nothing
        |> ResolvedValue.optional "gap" ResolvedValue.int Nothing


component : Component msg
component =
    register propsDecoder (\_ -> ()) (\_ -> ()) view


view : ComponentContext StackProps () () msg -> Html msg
view ctx =
    let
        dirClass =
            case ctx.props.direction of
                Just Horizontal ->
                    "jr-stack-horizontal"

                _ ->
                    "jr-stack-vertical"

        gapStyle =
            case ctx.props.gap of
                Just g ->
                    [ style "gap" (String.fromInt g ++ "px") ]

                Nothing ->
                    []
    in
    div (class ("jr-stack " ++ dirClass) :: gapStyle) ctx.children
