{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type SmOrMdOrLgOrXl
   - smOrMdOrLgOrXlFromString
   - type alias TextProps
   - propsDecoder
   - component
-}


module Catalog.Components.Text exposing (TextProps, component, propsDecoder, viewStateless)

import Dict exposing (Dict)
import Html exposing (Html, span, text)
import Html.Attributes exposing (class)
import JsonRender.Render exposing (Component, ComponentContext, register)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type SmOrMdOrLgOrXl
    = Sm
    | Md
    | Lg
    | Xl


smOrMdOrLgOrXlFromString : String -> Result String SmOrMdOrLgOrXl
smOrMdOrLgOrXlFromString str =
    case str of
        "sm" ->
            Ok Sm

        "md" ->
            Ok Md

        "lg" ->
            Ok Lg

        "xl" ->
            Ok Xl

        _ ->
            Err ("Unknown value: " ++ str ++ ". Expected one of: sm, md, lg, xl")


smOrMdOrLgOrXlToString : SmOrMdOrLgOrXl -> String
smOrMdOrLgOrXlToString value =
    case value of
        Sm ->
            "sm"

        Md ->
            "md"

        Lg ->
            "lg"

        Xl ->
            "xl"


type alias TextProps =
    { content : String, size : Maybe SmOrMdOrLgOrXl }


propsDecoder : Dict String ResolvedValue -> Result String TextProps
propsDecoder =
    ResolvedValue.succeed TextProps
        |> ResolvedValue.required "content" ResolvedValue.string
        |> ResolvedValue.optional
            "size"
            (\rv -> ResolvedValue.string rv |> Result.andThen smOrMdOrLgOrXlFromString)
            Nothing


component : Component msg
component =
    register propsDecoder (\_ -> ()) (\_ -> ()) view


viewStateless : TextProps -> Html msg
viewStateless props =
    let
        sizeClass =
            case props.size of
                Just s ->
                    "jr-text-" ++ smOrMdOrLgOrXlToString s

                Nothing ->
                    "jr-text-md"
    in
    span [ class ("jr-text " ++ sizeClass) ] [ text props.content ]


view : ComponentContext TextProps () () msg -> Html msg
view ctx =
    viewStateless ctx.props
