{- This module was generated by the CatalogSync elm-review rule.
   These values were created by the rule, and will be overwritten by it if changed:
   - type alias ToggleProps
   - propsDecoder
   - component
-}


module Catalog.Components.Toggle exposing (component, view)

import Dict exposing (Dict)
import Html exposing (Html, button, div, text)
import Html.Attributes exposing (class)
import Html.Events
import JsonRender.Actions as Actions
import JsonRender.Render exposing (Component, ComponentContext, registerStateful)
import JsonRender.Resolve as ResolvedValue exposing (ResolvedValue)


type alias ToggleProps =
    { label : String }


propsDecoder : Dict String ResolvedValue -> Result String ToggleProps
propsDecoder =
    ResolvedValue.succeed ToggleProps |> ResolvedValue.required "label" ResolvedValue.string


type alias State =
    { active : Bool }


type LocalMsg
    = ToggleClicked


component : Component (Actions.Msg action)
component =
    registerStateful propsDecoder (\_ -> ()) (\_ -> ())
        { init = \_ -> { active = False }
        , update =
            \ToggleClicked state _ ->
                ( { state | active = not state.active }, [] )
        , view = toggleView
        }


view : ComponentContext ToggleProps () () (Actions.Msg action) -> Html (Actions.Msg action)
view _ =
    text ""


toggleView : State -> ToggleProps -> (LocalMsg -> Actions.Msg action) -> List (Html (Actions.Msg action)) -> Html (Actions.Msg action)
toggleView state props toMsg _ =
    div [ class "jr-toggle" ]
        [ Html.map toMsg
            (button
                [ class "jr-toggle-btn"
                , Html.Events.onClick ToggleClicked
                ]
                [ text
                    (props.label
                        ++ ": "
                        ++ (if state.active then
                                "ON"

                            else
                                "OFF"
                           )
                    )
                ]
            )
        ]
